### ISSUE TITLE
Clicking JSON produces unexpected outcome...

### ISSUE THREAD

**Issue by harryharrold** [neontribe/gbptm-ui#29]
Steps to reproduce:

1) Go to http://greatbritishpublictoiletmap.rca.ac.uk/loos/54c2347a2ec4abe957b83a91

2) Click on JSON (Column, left hand side, 2/3 of the way down...)

3) Expected: JSON displayed, Actual: Map displayed?

**Comment by marxian** [comment]
Fixed
